# This is a basic workflow that is manually triggered

name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on: workflow_dispatch

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  
  # also practice checking out github
  pull_data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          persist-credentials: false
          fetch-depth: 0
          ref: ${{ github.head_ref }}

      # If using Python:
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"

      # If using Python:
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests pandas python-snappy pyarrow

      # If using Python:
      - name: Update data
        run: python3 scripts/update_datafiles.py

      - name: Commit changes to datafiles
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Apply data updates
