# This is a basic workflow that is manually triggered

name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on: workflow_dispatch

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  
  # also practice checking out github
  pull_data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          persist-credentials: false
          fetch-depth: 0
          ref: ${{ github.head_ref }}

      # If using Python:
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"

      # If using Python:
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests pandas python-snappy pyarrow

      # If using Python:
      - name: Update data
        run: python3 scripts/update_datafiles.py

      # NOTE: This commits everything in the `data` directory. Make sure this matches your needs
      - name: Git commit
        run: |
          git add *
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -m "Commiting data updates"

      # NOTE: Check that your branch name is correct here
      - name: Git push
        run: |
          git push "https://${GITHUB_ACTOR}:${TOKEN}@github.com/${GITHUB_REPOSITORY}.git" HEAD:main
        env:
          TOKEN: ${{ secrets.PAT }}
