# This is a basic workflow that is manually triggered

name: Install R

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on: workflow_dispatch

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  
  # also practice checking out github
  pull_data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          persist-credentials: false
          fetch-depth: 0

      # If using Python:
      - name: Set up R
        uses: r-lib/actions/setup-r@v1
        with:
          r-version: "3.5.3"

      - name: Install dependencies
        run: Rscript -e 'install.packages("nflfastR")'
        
      
